README.md
demo/Dockerfile
demo/Makefile
demo/README.md
demo/enable-theme.groovy
demo/jenkins3.sh

Now you an also use the demo for evaluating the UI preview mode with the dark theme and for development. Development is limited, because browsing caching is too good. So there is no stable live reload at the moment unfortunately.

Add Development and UI Preview modes to the Dark theme demo

---

demo/Dockerfile

Updates the demo to https://github.com/jenkinsci/jenkins/pull/4752/commits/fbdd4d72bf5a1a0837af035891da344a98232e3f

Upda the demo to the recent core build version

---

demo/Dockerfile

As reported by @ksenia-nenasheva , the demo does not work when using the DockerHub image. The file permissions are wrong. My local build passes permissions, but Docker for Windows might be messing with permissions. So I am applying a quick fix.

Fix permissions for the exec file on DockerHub

---

demo/Dockerfile

Now the demo uses a Jenkins weekly release so that there is no custom build hacks included.
Base image changelog: https://github.com/oleg-nenashev/demo-jenkins-config-as-code/releases

Update the demo to use Jenkins 2.239

---

src/main/resources/io/jenkins/plugins/darktheme/theme.css

Requires https://github.com/jenkinsci/jenkins/pull/4843
Fixes https://github.com/jenkinsci/dark-theme-plugin/issues/103
<details>
</details>
<details>
</details>

Theme text area handle

---

src/main/resources/io/jenkins/plugins/darktheme/theme.css

Fixes https://github.com/jenkinsci/dark-theme-plugin/issues/88
<details>
</details>
<details>
</details>
Thoughts @major-fire and @fqueiruga ?

Improve contrast for dark link colours

---

pom.xml

Latest table changes aren't backwards compatible so bumping minimum version to the one which introduced them

Bump minimum version to 2.248

---

README.md

Commit a15c7f9 bumped the required version of Jenkins to **2.248**.
However, the README still stated, that the minimum required version
was **2.239** which caused a bit of confusion, as I was not able to
update the theme without updating Jenkins first.

Update minimum required version to 2.248 in README

---

pom.xml
src/main/resources/io/jenkins/plugins/darktheme/theme.css

<details>
</details>
<details>
</details>
Also affects the sidepanel build queue

Fix colour's on 2.251

---

src/main/resources/io/jenkins/plugins/darktheme/theme.css

Override --white, fixes 'more info' link in empty states

---

.gitignore
package-lock.json
package.json
pom.xml
src/main/frontend/main.scss
src/main/java/io/jenkins/plugins/darktheme/DarkThemeManagerFactory.java
src/main/java/io/jenkins/plugins/darktheme/DarkThemeRootAction.java
src/main/java/io/jenkins/plugins/darktheme/DarkThemeSystemManagerFactory.java
src/main/resources/io/jenkins/plugins/darktheme/theme-system.css

See https://github.com/jenkinsci/theme-manager-plugin/pull/75
All themes are now loaded on every page, the active theme is controlled by a `data` attribute on the `html` element.
FYI @janfaracik

Add live theme switching support

---

src/main/frontend/main.scss

This PR adapts the changes from core, which dropped colors on breadcrumb links.
Also closes https://github.com/jenkinsci/dark-theme-plugin/issues/140

Use text color for dropdowns

---

src/main/frontend/main.scss

So browsers will default to a 'light' color scheme for native elements, setting the `color-scheme` attribute to `dark` will use a dark color scheme instead.
https://developer.mozilla.org/en-US/docs/Web/CSS/color-scheme
**Before**
**After**
Screenshots taken in Safari 15.4.

Set browser color scheme to 'dark'

---

src/main/frontend/main.scss

... so the new tooltips aren't blindingly white on dark theme. Uses the same styling as the prototype dark mode tooltips.

Add backdrop variable for new Tippy tooltips

---

src/main/frontend/main.scss

Adds the `backdrop-filter` and `box-shadow` vars necessary for [the search suggestions introduced in #7314](https://github.com/jenkinsci/jenkins/pull/7314).

Add dropdown colors

---

pom.xml
src/main/frontend/main.scss

**Few changes**
* Updates the variables to reflect the changes introduced in Jenkins 2.415 (https://github.com/jenkinsci/jenkins/pull/8219)
* Use `--accent-color` rather than `--primary`
* Add 'black' and 'white' to the list of colours
* Use `display-p3` and `color-mix` now that they're widely supported (and [Firefox ESR supports it too with v115](https://www.mozilla.org/en-US/firefox/115.0esr/releasenotes/))
* Tweak the input background/border as the hue was off
* Removed some deprecated, unused variables
**Before**
**After**
* Jenkins works the same in all major browsers according to https://www.jenkins.io/doc/administration/requirements/web-browsers/
* Had a scan through various pages and all look fine (including Design Library)
```[tasklist]
```

Tweaking some colours + tidy up

---

src/main/frontend/main.scss

Fixes #205 by making the icon (and search field content) slightly darker by default and lighter on hover.
```[tasklist]
```

Darker color for search, highlight search help icon on hover

---

pom.xml

Now that the baseline is available in LTS form, prefer it for the reasons given in [the documentation](https://www.jenkins.io/doc/developer/plugin-development/choosing-jenkins-baseline/).

Require Jenkins 2.426.1 LTS or newer

---

src/main/frontend/main.scss

Should fix https://github.com/jenkinsci/dark-theme-plugin/pull/433#issuecomment-1878655575
Checked that login button color is as expected:
and search is still highlighting OK
```[tasklist]
```

Restrict header highlighting to search form

---

src/main/frontend/main.scss

Had removed this by mistake in the last PR - this fixes the weird border issue on tables.
**Before**
**After**
```[tasklist]
```

Fix table border

---

pom.xml
src/main/frontend/main.scss

With https://github.com/jenkinsci/jenkins/pull/9115 it's no longer necessary for themes to set alert style variables - so this merge request removes them. 
Can either have the minimum Jenkins version be set to the weekly that contains the above MR or I can set the variables here with a comment that they can eventually be removed.
**Before 9115**
**After 9115**
```[tasklist]
```

Remove alert styles

---

src/main/java/io/jenkins/plugins/darktheme/DarkThemeManagerFactory.java
src/main/java/io/jenkins/plugins/darktheme/DarkThemeSystemManagerFactory.java

Following https://github.com/jenkinsci/prism-api-plugin/pull/161 it's no longer necessary for Jenkins themes to declare what theme Prism should use. This is due to the default Prism theme now using the default Jenkins colour palette for its colours, meaning that as long as themes override them Prism will pick them up automatically.
**Before**
**After**
* Prism looks as expected
```[tasklist]
```

Use Jenkins colour palette for Prism instead of `tomorrow`

---

src/main/frontend/main.scss

Currently, scrollbars aren't dark in Chrome:
with this change it will look like this:

fix: render dark scrollbars in dark mode

---

src/main/frontend/main.scss

Small one to stop using translucent colors for cards/tables/tabs. This isn't really an issue in 'core' but in the Design Library the components can look a little odd when overlaying a colorful background (the color bleeds through). There shouldn't be any differences in 'core', apart from perhaps an unnoticeable hue change.
**Before**
**After**
* Cards/tables/tabs look as expected

Don't use a translucent color for cards/tables/tabs

---

.gitattributes
Jenkinsfile

Jenkins stopped supporting Java 11 with the release of Jenkins 2.463 (weekly) and Jenkins 2.479.1 (LTS).  Most plugins stopped spending ci.jenkins.io time to run tests that are specific to Java 11.
Let's save money and time by removing the Java 11 test configuration.  It has not found any issues that are not also found with Java 17 and Java 21.
Jenkins plugin BOM still tests with Java 11 on older lines (currently 2.452.x and 2.462.x) and the plugin build will continue to generate Java 11 byte code until the parent pom is upgraded to 5.x and the minimum Jenkins version is upgraded to 2.479.1.
Switch to test Windows with Java 17 since that matches the plugin archetype.
Explicitly declares the file types of source files to avoid the git client plugin bug that performs a checkout with Windows …

Stop testing Java 11
