jenkinsci/dark-theme-plugin

README.md, demo/Dockerfile, demo/Makefile, demo/README.md, demo/enable-theme.groovy, demo/plugins.txt
Does not work, I likely need a new incrementals version
=> Add a quick-start demo for the Dark Theme

theme.css
See https://github.com/timja/jenkins/pull/3, https://github.com/timja/jenkins/pull/4
=> Updates to match variables renames in core

theme.css
Update variables to reflect current Jenkins API﻿
=> Update to current API in Jenkins

theme.css
Only the auto complete dropdown isn't working
=> Mostly complete newJob view

demo/README.md
closes #15 
* https://hub.docker.com/r/jenkins4eval/dark-theme
* Builds are automated for the master branch
=> Deploy the demo to DockerHub

.all-contributorsrc, CONTRIBUTING.md, CONTRIBUTORS.md, README.md
=> Update contributing guidelines, introduce All Contributors

theme.css
Fixes https://github.com/jenkinsci/dark-theme/issues/30
=> Add theme for script-console

theme.css
Fixes https://github.com/jenkinsci/dark-theme/issues/20
=> Fix update center

theme.css
=> Fix autocomplete on addJob and active addJob

.github/workflows/release-drafter.yml, README.md
Fixes https://github.com/jenkinsci/dark-theme/issues/18
Fixes https://github.com/jenkinsci/dark-theme/issues/46
=> Add release drafter, browser compat, use tags

theme.css
=> Fix v2 header

demo/README.md
=> Demo - Add a link to the DockerHub badge

demo/README.md
Reverts jenkinsci/dark-theme#69
=> Revert "Demo - Add a link to the DockerHub badge"

theme.css
Fixes https://github.com/jenkinsci/dark-theme/issues/31
Requires https://github.com/jenkinsci/jenkins/pull/4761
=> Fix contrast on all views

demo/jenkins3.sh
DockerHub builds the demo image differently from my local computer (Docker for Windows)
=> Fix permissions in the demo launcher file

demo/README.md
Reverts jenkinsci/dark-theme#71
Wrong revert 🤦
=> Revert "Revert "Demo - Add a link to the DockerHub badge""

demo/Dockerfile
Reverts jenkinsci/dark-theme#70
=> Revert "Fix permissions for the exec file on DockerHub"

theme.css
=> Adapt for new sidepanel changes

README.md, theme-system.css
Fixes https://github.com/jenkinsci/dark-theme/issues/86
=> Add respect of system configuration

.github/workflows/release-drafter.yml
Blindly copied from: https://github.com/release-drafter/release-drafter/pull/424#issuecomment-636604700
=> Fix typo in release drafter config

demo/Dockerfile, demo/Makefile, demo/enable-theme.groovy, demo/jenkins3.sh, demo/plugins.txt
Just an initial cleanup of the demo. I will update the demo to use the published plugins in a follow-up
=> Update the demo to use Jenkins 2.240 and recent plugins

src/main/resources/io/jenkins/plugins/darktheme/theme.css
Fixes https://github.com/jenkinsci/dark-theme-plugin/issues/105
=> Theme transparent buttons

src/main/resources/io/jenkins/plugins/darktheme/theme.css
ref https://github.com/jenkinsci/dark-theme-plugin/pull/106#issuecomment-647695615
@fqueiruga 
left active, right hover
=> Add active state for transparent buttons

src/main/resources/io/jenkins/plugins/darktheme/theme.css
ref https://github.com/jenkinsci/jenkins/pull/4782
No changes for dark theme, but looks bad otherwise
=> Update manage variables for upcoming core

src/main/resources/io/jenkins/plugins/darktheme/theme.css
see https://github.com/jenkinsci/jenkins/pull/4835 
Fixes https://github.com/jenkinsci/dark-theme-plugin/issues/113
Will bump the core version when we know which version it will be in
=> Adapt table changes in core

src/main/resources/io/jenkins/plugins/darktheme/theme.css
Fixes https://github.com/jenkinsci/dark-theme-plugin/issues/98
Fixes https://github.com/jenkinsci/dark-theme-plugin/issues/102
Requires: https://github.com/jenkinsci/jenkins/pull/4842
<details>
</details>
<details>
</details>
Thoughts?
=> Theme alerts

src/main/resources/io/jenkins/plugins/darktheme/theme.css
Based on feedback from @daniel-beck in https://github.com/jenkinsci/dark-theme-plugin/pull/114#issuecomment-660631183
<details>
</details>
<details>
</details>
=> Adjust alerts theming

src/main/resources/io/jenkins/plugins/darktheme/theme.css
Missed in https://github.com/jenkinsci/dark-theme-plugin/pull/116
=> Fix style flash with tab bar in new tables change

src/main/resources/io/jenkins/plugins/darktheme/theme.css
Text area handle was changed to use colours instead of a new variable at the last minute, forgot to update here.
I've also fixed https://github.com/jenkinsci/dark-theme-plugin/issues/110 while I was there
=> Fix text area handle

src/main/resources/io/jenkins/plugins/darktheme/theme.css
<details>
</details>
<details>
</details>
=> Update big table header color

src/main/resources/io/jenkins/plugins/darktheme/theme.css
Fixes https://github.com/jenkinsci/dark-theme-plugin/issues/136
=> Plugin manager text contrast improvements

src/main/resources/io/jenkins/plugins/darktheme/theme.css
Based on feedback in IRC
Before:
After:
=> Tweak header colour's

README.md, pom.xml
There's 2 not backported fixes:
https://issues.jenkins-ci.org/browse/JENKINS-63330
https://issues.jenkins-ci.org/browse/JENKINS-63331
But let's get this out to users, those issues are minor
=> Set minimum version to LTS

src/main/resources/io/jenkins/plugins/darktheme/theme.css
<details><summary>Before</summary>
</details>
<details><summary>After</summary>
</details>
It would also be nice to fix the grey on pink, but I couldn't tell off the top of my head how to.
=> Improve hyperlink contrast

pom.xml, src/main/resources/io/jenkins/plugins/darktheme/theme.css
See https://github.com/jenkinsci/jenkins/pull/5176
It looks largely the same...
=> Adapt to core accessibility and color palette changes

pom.xml, src/main/resources/io/jenkins/plugins/darktheme/theme.css
* Update colors for new forms/table design
Some screenshots
=> Update colors for new forms/table design

src/main/resources/io/jenkins/plugins/darktheme/theme.css
* Adds the appropriate colors for new `<pre/>` styling introduced in [Jenkins #6259](https://github.com/jenkinsci/jenkins/pull/6259) and selection color
---
=> Add colors for new <pre/> styling and selection color

src/main/frontend/main.scss
Requires https://github.com/jenkinsci/jenkins/pull/6350 
Fixes https://github.com/jenkinsci/dark-theme-plugin/issues/168
=> Make plugin "Unavailable" label readable

src/main/frontend/main.scss
Tiny PR to add the new vars for the [tooltips PR](https://github.com/jenkinsci/jenkins/pull/6408).  
---
=> Add colors for new Jenkins tooltips

src/main/frontend/main.scss
=> Add support for the new range of colours in Jenkins

renovate.json
Shipped by the default config, but I forgot to add it, oops.
=> chore: Add renovate schema URL

src/spotbugs/excludesFilter.xml
Removed now unneeded spotbugs filter, since the issue is resolved: https://github.com/spotbugs/spotbugs/issues/756
=> Removed now unneeded spotbugs filter

pom.xml, renovate.json
Node 18.x is the next LTS version, ftr.
=> Update node to 18.x and npm to 9.x

src/main/java/io/jenkins/plugins/darktheme/DarkThemeRootAction.java
=> Removed unused imports

src/main/java/io/jenkins/plugins/darktheme/DarkThemeManagerFactory.java, src/main/java/io/jenkins/plugins/darktheme/DarkThemeSystemManagerFactory.java
When consumed by https://github.com/jenkinsci/workflow-cps-plugin/pull/654, fixes https://github.com/jenkinsci/dark-theme-plugin/issues/127.
=> Add support for ACE Editor

src/main/java/io/jenkins/plugins/darktheme/DarkThemeSystemManagerFactory.java
See https://github.com/jenkinsci/workflow-cps-plugin/pull/654#pullrequestreview-1287070582
I'm starting to look into supporting this properly but this will do to unblock the above for now
=> Remove dark themes properties from system mode for now

src/main/frontend/main.scss
For https://github.com/jenkinsci/jenkins/pull/7718
=> Add modal colors

src/main/frontend/main.scss
this change adds the classes required by dialogs
See https://github.com/jenkinsci/jenkins/pull/7938
Should be only merged once the change in core is accepted and merged.
```[tasklist]
```
=> Support for upcoming dialogs

pom.xml, src/main/java/io/jenkins/plugins/darktheme/DarkThemeSystemManagerFactory.java
Requires https://github.com/jenkinsci/theme-manager-plugin/pull/171
=> Add properties for system theme

README.md
Closes https://github.com/jenkinsci/dark-theme-plugin/issues/412
```[tasklist]
```
=> Remove outdated simple theme plugin instructions

README.md
Fixes #422, change based from https://github.com/jenkinsci/theme-manager-plugin/pull/210
Checked that readme markdown changes are valid
```[tasklist]
```
=> Update JCasC usage in readme

src/main/frontend/main.scss
Sets the variables for cards, so they appear [consistent with the prototype](http://jenkins-redesign.vercel.app).
**Before**
**After**
Using `jenkins#new-build-history-2` for the above images
* Cards appear as expected
```[tasklist]
```
=> Set card variables

src/main/java/io/jenkins/plugins/darktheme/DarkThemeManagerFactory.java, src/main/java/io/jenkins/plugins/darktheme/DarkThemeSystemManagerFactory.java
Tested in the AzureAd plugin using https://learn.microsoft.com/en-us/graph/toolkit/customize-components/style
```[tasklist]
```
=> Add Entra ID theme

src/main/java/io/jenkins/plugins/darktheme/DarkThemeSystemManagerFactory.java
=> Fix typo for system dark theme with entra id

src/main/resources/index.jelly
Adds a more detailed description what this plugin does, given we do now respect browser and OS themes properly :)
=> Update plugin manager description

README.md
Fixes https://github.com/jenkinsci/dark-theme-plugin/issues/447
Given it's in LTS now I think it should be ok, if we get some confusion we can add some temp docs about previous LTS versions
```[tasklist]
```
=> Update docs for using appearance page

pom.xml, src/main/frontend/main.scss
**Before**
**After**
* Tables/tabs use lighter styling now, inline with the cards UI and the prototype - https://jenkins-redesign.vercel.app (an MR will eventually be made to make the colours actually consistent between core and the prototype)
```[tasklist]
```
=> Update table styling

pom.xml, src/main/java/io/jenkins/plugins/darktheme/DarkThemeManagerFactory.java, src/main/java/io/jenkins/plugins/darktheme/DarkThemeRootAction.java, src/main/java/io/jenkins/plugins/darktheme/DarkThemeSystemManagerFactory.java, src/test/java/io/jenkins/plugins/darktheme/jcasc/dark/DarkThemeJcascTest.java, src/test/java/io/jenkins/plugins/darktheme/jcasc/darksystem/DarkSystemThemeJcascTest.java
Signed-off-by: Alexander Brandes <mc.cache@web.de>
```[tasklist]
```
=> Apply spotless

src/main/frontend/main.scss
Adds support for the command palette in https://github.com/jenkinsci/jenkins/pull/7569
```[tasklist]
```
=> Add command palette colours

.github/renovate.json
Based on https://github.com/jenkinsci/pipeline-graph-view-plugin/blob/main/.github/renovate.json
=> Migrate to standard node.js renovate updater

src/main/frontend/main.scss
Should fix https://github.com/jenkinsci/dark-theme-plugin/issues/609 (I don't have a Windows/Linux machine to test on).
Fixes some of the border colors too, so they're consistent with one another and are more defined. Some changes will be needed in _core_ in the future to standardise these - but for the time being this works.
**Before**
**After**
**Before**
**After**
=> Fix input and border colors

pom.xml, src/main/java/io/jenkins/plugins/darktheme/DarkThemeManagerFactory.java, src/main/java/io/jenkins/plugins/darktheme/DarkThemeSystemManagerFactory.java
For https://github.com/jenkinsci/theme-manager-plugin/pull/317
=> Add icon for account theme picker
